stages:
    - build
    - deploy

buildImage:
    stage: build
    script:
        - docker build -t shibesbot:latest .

removeOldContainer:
    stage: build
    variables:
        CONTAINER_EXISTS: $(docker ps -a | grep shibesbot)
        CONTAINER_RUNNING: $(docker container inspect -f '{{.State.Running}}' shibesbot)
    script:
        - >
            if ["$CONTAINER_EXISTS" == "true"]; then
                if ["$CONTAINER_RUNNING" == "true"]; then
                    docker stop shibesbot
                fi
                docker rm shibesbot
            fi

runContainer:
    stage: deploy
    script:
        - docker run -d -e DISCORD_TOKEN=${DISCORD_TOKEN} --name shibesbot shibesbot:latest
